# Generated by Django 4.2.4 on 2023-08-29 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_flower_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flowers', to='core.category'),
        ),
    ]
